#!/bin/bash


##DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


DIR="/home/mriantf/script_skripsi"
OUTPUT="${DIR}/OUTPUT"
RRALOC="/var/www/html/cacti/rra"

REPORT_ID=$1
GTYPE=$2
FILENAME=$3
RRDNAME=$4
RRDFILE$5

DATE_FN=`date '+%Y%m%d'`

INTERVAL=`date -d 'now-31days' +%s`
NOW=`date -d now +%s`

for((i=$INTERVAL; i<=$NOW; i+=518400))
do
    START=`date -d @${i} '+%Y/%m/%d %H\:%M\:%S'`
    j=$(($i+86400))
    END=`date -d @${j} '+%Y/%m/%d %H\:%M\:%S'`

    /usr/bin/rrdtool graph ${OUTPUT}/${GTYPE}/${REPORT_ID}_${DATE_FN}_${GTYPE}_${FILENAME}.png \
	--imgformat=PNG \
	--start="${i}" \
	--end="${j}" \
	--pango-markup  \
	--title="${RRDNAME}" \
	--vertical-label='bits/sec' \
	--slope-mode \
	--base=1000 \
	--height=120 \
	--width=500 \
	--rigid \
	--alt-autoscale-max \
	--lower-limit='0' \
	COMMENT:"From ${START} To ${END}\c" \
	COMMENT:"  \n" \
	--color BACK#F3F3F3 \
	--color CANVAS#FDFDFD \
	--color SHADEA#CBCBCB \
	--color SHADEB#999999 \
	--color FONT#000000 \
	--color AXIS#2C4D43 \
	--color ARROW#2C4D43 \
	--color FRAME#2C4D43 \
	--border 1 --font TITLE:11:'Arial' \
	--font AXIS:8:'Arial' \
	--font LEGEND:8:'Courier' \
	--font UNIT:8:'Arial' \
	--font WATERMARK:6:'Arial' \
	--slope-mode \
	--watermark 'Generated by Cacti®' \
	DEF:a="${RRALOC}/${RRDFILE}":'traffic_in':MAX \
	DEF:b="${RRALOC}/${RRDFILE}":'traffic_in':AVERAGE \
	DEF:c="${RRALOC}/${RRDFILE}":'traffic_out':AVERAGE \
	DEF:d="${RRALOC}/${RRDFILE}":'traffic_out':MAX \
	CDEF:cdefa='a,8,*' \
	CDEF:cdefb='b,8,*' \
	CDEF:cdeff='c,8,*' \
	CDEF:cdefg='d,8,*' \
	LINE1:cdefa#00CF00FF:  \
	AREA:cdefb#00CF00FF:'Inbound '  \
	GPRINT:cdefb:LAST:'Current\:%8.2lf%s'  \
	GPRINT:cdefb:AVERAGE:'Average\:%8.2lf%s'  \
	GPRINT:cdefb:MAX:'Maximum\:%8.2lf%s\n'  \
	LINE1:cdeff#002A97FF:'Outbound'  \
	LINE1:cdefg#002A97FF:  \
	GPRINT:cdefg:LAST:'Current\:%8.2lf%s'  \
	GPRINT:cdefg:AVERAGE:'Average\:%8.2lf%s'  \
	GPRINT:cdefg:MAX:'Maximum\:%8.2lf%s' 
done