#!/bin/bash


##DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


DIR="/home/mriantf/script_skripsi"
DT_RP="${DIR}/DATA_REPORT"
WORKDIR="${DIR}/script"
OUTPUT="${DIR}/OUTPUT"
RRALOC="/var/www/html/cacti/rra"

DATE_FN=`date '+%Y%m%d'`

LAST24=`date -d now-1days +%s`
NOW=`date -d now +%s`

START=`date -d @${LAST24} '+%Y/%m/%d %H\:%M\:%S'`
ENDTIME=`date -d @${NOW} '+%Y/%m/%d %H\:%M\:%S'`

LIST_REPORT=("Daily"
"Weekly"
"Monthly"
)


for i in "${LIST_REPORT[@]}"
do
  ls ${DT_RP}/${i} > ${WORKDIR}/tmp_list
  for j in `cat ${WORKDIR}/tmp_list`
  do
    cat ${DT_RP}/${i}/${j} | while read line
	do
	  REPORT_NAME=`echo $line | awk -F';' '{print $4}'`
	  GTYPE=`echo $line | awk -F';' '{print $5}'`
	  RRDFILE=`echo $line | awk -F';' '{print $6}'`
	  RRDNAME=`echo $line | awk -F';' '{print $7}'`
	  FILENAME=`echo $line | awk -F';' '{print $7}' | sed 's/ /_/g' | sed 's/\//-/g'`
	  
	  #coba 24 jam terakhir
	  /usr/bin/rrdtool graph ${OUTPUT}/${i}/${DATE_FN}_${GTYPE}_${FILENAME}.png \
		--imgformat=PNG \
		--start="${LAST24}" \
		--end="${NOW}" \
		--pango-markup  \
		--title="${RRDNAME}" \
		--vertical-label='bits/sec' \
		--slope-mode \
		--base=1000 \
		--height=120 \
		--width=500 \
		--rigid \
		--alt-autoscale-max \
		--lower-limit='0' \
		COMMENT:"From ${START} To ${ENDTIME}\c" \
		COMMENT:"  \n" \
		--color BACK#F3F3F3 \
		--color CANVAS#FDFDFD \
		--color SHADEA#CBCBCB \
		--color SHADEB#999999 \
		--color FONT#000000 \
		--color AXIS#2C4D43 \
		--color ARROW#2C4D43 \
		--color FRAME#2C4D43 \
		--border 1 --font TITLE:11:'Arial' \
		--font AXIS:8:'Arial' \
		--font LEGEND:8:'Courier' \
		--font UNIT:8:'Arial' \
		--font WATERMARK:6:'Arial' \
		--slope-mode \
		--watermark 'Generated by Cacti®' \
		DEF:a="${RRALOC}/${RRDFILE}":'traffic_in':MAX \
		DEF:b="${RRALOC}/${RRDFILE}":'traffic_in':AVERAGE \
		DEF:c="${RRALOC}/${RRDFILE}":'traffic_out':AVERAGE \
		DEF:d="${RRALOC}/${RRDFILE}":'traffic_out':MAX \
		CDEF:cdefa='a,8,*' \
		CDEF:cdefb='b,8,*' \
		CDEF:cdeff='c,8,*' \
		CDEF:cdefg='d,8,*' \
		LINE1:cdefa#00CF00FF:  \
		AREA:cdefb#00CF00FF:'Inbound '  \
		GPRINT:cdefb:LAST:'Current\:%8.2lf%s'  \
		GPRINT:cdefb:AVERAGE:'Average\:%8.2lf%s'  \
		GPRINT:cdefb:MAX:'Maximum\:%8.2lf%s\n'  \
		LINE1:cdeff#002A97FF:'Outbound'  \
		LINE1:cdefg#002A97FF:  \
		GPRINT:cdefg:LAST:'Current\:%8.2lf%s'  \
		GPRINT:cdefg:AVERAGE:'Average\:%8.2lf%s'  \
		GPRINT:cdefg:MAX:'Maximum\:%8.2lf%s' 
	  
	  
	done < ${DT_RP}/${i}/${j}
  done
done
rm -rf ${WORKDIR}/tmp_list
